import type { LetterType } from '@/lib/letters/templates';

export const EN_TEMPLATE_HTML: Record<LetterType, string> = {
  'general': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">
  <style>
    .var { font-weight: bold; }
    .top-row { display: flex; justify-content: space-between; margin-bottom: 18px; }
    .recipient { margin-bottom: 14px; font-weight: normal; }
    .subject { font-weight: bold; margin-bottom: 14px; }
    .paragraph { text-align: justify; text-indent: 35px; margin: 0 0 8px 0; padding: 0; font-weight: normal; }
    .paragraph:last-of-type { margin-bottom: 0; }
  </style>
  <div class="top-row">
    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>
    <div>Date: <span class="var">{{date}}</span></div>
  </div>
  <div class="recipient">{{toBlock}}</div>
  <div class="subject"><span style="font-weight: normal;">Subject:</span> <span class="var">{{subject}}</span></div>
  {{paragraphsBlock}}
  <div class="letter-closing">{{signatureBlock}}</div>
</div>`,
  'fees': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 13px; line-height: 1.55; color: #000; margin: 0; font-weight: normal;">
  <style>
    .var { font-weight: bold; }
    .top-row { display: flex; justify-content: space-between; margin-bottom: 12px; }
    .address { margin-bottom: 12px; font-weight: normal; }
    .subject { font-weight: bold; margin-bottom: 12px; }
    .salutation { margin-bottom: 6px; font-weight: normal; }
    .paragraph { text-align: justify; text-indent: 28px; margin: 0 0 8px 0; padding: 0; font-weight: normal; }
    .paragraph:last-of-type { margin-bottom: 0; }
    .right-tab { text-align: right; padding-right: 36px; margin-top: 18px; font-weight: normal; }
    .right-tab-sign { text-align: right; padding-right: 28px; margin-top: 75px; font-weight: normal; }
  </style>
  <div class="top-row">
    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>
    <div>Date: <span class="var">{{date}}</span></div>
  </div>
  <div class="address">
    To,<br>
    Headmaster / Principal,<br>
    <span style="font-weight: normal;">{{schoolName}}</span><br>
    <span style="font-weight: normal;">{{schoolAddress}}</span>
  </div>
  <div class="subject">
    <span style="font-weight: normal;">Subject:</span> Request for fee concession for student <span class="var">{{studentName}}</span> in <span class="var">{{standard}}</span>
  </div>
  <div class="salutation">
    Sir/Madam,
  </div>
  <p class="paragraph">
    Through this letter, I request that fee concession be granted to <span class="var">{{studentName}}</span>, a student studying in <span class="var">{{standard}}</span> at your school.
  </p>
  <p class="paragraph">
    The financial condition of the student's parents is extremely weak, and they are currently unable to pay the full fees. Therefore, I humbly request you to kindly consider granting a full or partial fee concession, and also provide additional time and/or instalment facility for fee payment.
  </p>
  <p class="paragraph">
    Also, kindly permit the said student to attend school/college regularly so that there is no adverse effect on the student's education.
  </p>
  <p class="paragraph">
    I hope you will consider this matter sympathetically and take a positive decision.
  </p>
  <div class="letter-closing">
  <div class="right-tab">
    Yours faithfully,
  </div>
  <div class="right-tab-sign">
    (<span class="var">{{signatory}}</span>)
  </div>
  </div>
</div>`,
  'school-admission': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    To,<br>    Headmaster / Principal,<br>    <span style="font-weight: normal;">{{schoolName}}</span><br>    <span style="font-weight: normal;">{{schoolAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Recommendation for admission of student <span class="var">{{studentName}}</span> to Standard <span class="var">{{standard}}</span>.  </div>  <div class="salutation">    Sir/Madam,  </div>  <p class="paragraph">    Through this letter, <span class="var">{{studentName}}</span>, child of <span class="var">{{parentName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is hereby recommended to you for admission to Standard <span class="var">{{standard}}</span> at your school.  </p>  <p class="paragraph">    The said student has an interest in education, and a proper academic environment is necessary for further studies. Admission to Standard <span class="var">{{standard}}</span> at your school will certainly help the student's education.  </p>  <p class="paragraph">    <span class="var">{{reasonText}}</span>  </p>  <p class="paragraph">    Kindly verify the availability of seats, admission rules, and required documents, and take necessary action as per rules to grant admission to Standard <span class="var">{{standard}}</span> at your school to the said student.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'school-transfer': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    To,<br>    Headmaster / Principal,<br>    <span style="font-weight: normal;">{{schoolName}}</span><br>    <span style="font-weight: normal;">{{schoolAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Recommendation for transfer admission of student <span class="var">{{studentName}}</span> to Standard <span class="var">{{standard}}</span>.  </div>  <div class="salutation">    Sir/Madam,  </div>  <p class="paragraph">    Through this letter, <span class="var">{{studentName}}</span>, child of <span class="var">{{parentName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is hereby recommended to you for transfer admission to Standard <span class="var">{{standard}}</span> at your school.  </p>  <p class="paragraph">    The said student is currently studying in Standard <span class="var">{{currentStandard}}</span> at <span class="var">{{previousSchoolName}}</span>, and due to <span class="var">{{transferReason}}</span>, it has become necessary for the student to seek admission to Standard <span class="var">{{standard}}</span> at your school.  </p>  <p class="paragraph">    To ensure that there is no break in the student's education and that further studies continue smoothly, admission to Standard <span class="var">{{standard}}</span> at your school is extremely necessary.  </p>  <p class="paragraph">    Kindly verify the availability of seats, admission rules, school leaving certificate / transfer certificate, and required documents, and take necessary action as per rules to grant transfer admission to Standard <span class="var">{{standard}}</span> at your school to the said student.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'ration-new': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding issuance of a new ration card.  </div>  <p class="paragraph">    Along with this letter, the applicant <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is being forwarded to you for obtaining a new ration card.  </p>  <p class="paragraph">    The applicant has submitted an application along with the required documents for a new ration card, and a request is being made to include the following family members in the new ration card:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for approving a new ration card.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    To,<br>    Rationing Officer,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-add-members': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding addition of names to ration card.  </div>  <p class="paragraph">    Along with this letter, the applicant <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is being forwarded to you for addition of family members' names to their ration card.  </p>  <p class="paragraph">    The applicant's ration card number is <span class="var">{{rationCardNo}}</span>, and a request is being made to include the following members' names in the said ration card:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for adding the said members' names to the ration card.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    To,<br>    Rationing Officer,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-delete-members': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding deletion of names from ration card.  </div>  <p class="paragraph">    Along with this letter, the applicant <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is being forwarded to you for deletion of family members' names from their ration card.  </p>  <p class="paragraph">    The applicant's ration card number is <span class="var">{{rationCardNo}}</span>, and a request is being made to delete the following members' names from the said ration card:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for deleting the said members' names from the ration card.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    To,<br>    Rationing Officer,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-transfer': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding transfer of ration card from one rationing office to another.  </div>  <p class="paragraph">    Along with this letter, the applicant <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is being forwarded to you for transfer of their ration card.  </p>  <p class="paragraph">    The applicant's ration card number is <span class="var">{{rationCardNo}}</span>, and a request is being made to transfer the said ration card from <span class="var">{{fromRationOffice}}</span> to <span class="var">{{toRationOffice}}</span>.  </p>  <p class="paragraph">    Due to change in the applicant's place of residence / change in area, it is necessary to transfer the said ration card to the jurisdiction of the relevant new rationing office.  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for transferring the said ration card to <span class="var">{{toRationOffice}}</span>.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    To,<br>    Rationing Officer,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'income': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    To,<br>    Concerned Officer,<br>    <span style="font-weight: normal;">{{officeName}}</span><br>    <span style="font-weight: normal;">{{officeAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding issuance of income certificate to <span class="var">{{fullName}}</span>.  </div>  <div class="salutation">    Sir/Madam,  </div>  <p class="paragraph">    Through this letter, it is informed that <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, is a resident at the above-mentioned address.  </p>  <p class="paragraph">    The applicant's Aadhaar number is <span class="var">{{aadhaarNo}}</span>, and as per the information provided by them, their annual income is Rs. <span class="var">{{annualIncome}}</span>/-.  </p>  <p class="paragraph">    This certificate / recommendation letter is being issued at the request of the applicant.  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for issuing the income certificate.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'domicile': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>Ref. No. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>Date: <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    To,<br>    Concerned Officer,<br>    <span style="font-weight: normal;">{{officeName}}</span><br>    <span style="font-weight: normal;">{{officeAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">Subject:</span> Regarding issuance of domicile / residence certificate to <span class="var">{{fullName}}</span>.  </div>  <div class="salutation">    Sir/Madam,  </div>  <p class="paragraph">    Through this letter, it is informed that <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, residing at <span style="font-weight: normal;">{{address}}</span>, has been residing at the above-mentioned address for a long period.  </p>  <p class="paragraph">    The applicant's Aadhaar number is <span class="var">{{aadhaarNo}}</span>, and they have requested issuance of a domicile / residence certificate.  </p>  <p class="paragraph">    Kindly verify the supporting documents available with the applicant and take necessary action as per rules for issuing the domicile / residence certificate.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
};
