import { INDIAN_STATES } from '@/lib/letters/pincode-lookup';

export { INDIAN_STATES };

/** Major cities / districts keyed by English state name. */
export const CITIES_BY_STATE: Record<string, readonly string[]> = {
  'Andhra Pradesh': [
    'Anantapur',
    'Chittoor',
    'East Godavari',
    'Guntur',
    'Kadapa',
    'Krishna',
    'Kurnool',
    'Nellore',
    'Prakasam',
    'Srikakulam',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari',
  ],
  'Arunachal Pradesh': [
    'Changlang',
    'East Kameng',
    'East Siang',
    'Itanagar',
    'Lohit',
    'Lower Subansiri',
    'Papum Pare',
    'Tawang',
    'Tirap',
    'Upper Siang',
    'Upper Subansiri',
    'West Kameng',
    'West Siang',
  ],
  Assam: [
    'Barpeta',
    'Cachar',
    'Darrang',
    'Dibrugarh',
    'Goalpara',
    'Golaghat',
    'Guwahati',
    'Jorhat',
    'Kamrup',
    'Karbi Anglong',
    'Karimganj',
    'Lakhimpur',
    'Nagaon',
    'Sivasagar',
    'Sonitpur',
    'Tinsukia',
  ],
  Bihar: [
    'Arrah',
    'Aurangabad',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur',
    'Darbhanga',
    'Gaya',
    'Muzaffarpur',
    'Nalanda',
    'Patna',
    'Purnia',
    'Saharsa',
    'Samastipur',
    'Saran',
    'Siwan',
  ],
  Chhattisgarh: [
    'Bastar',
    'Bilaspur',
    'Durg',
    'Jagdalpur',
    'Korba',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
  ],
  Goa: ['North Goa', 'Panaji', 'South Goa', 'Vasco da Gama'],
  Gujarat: [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Bharuch',
    'Bhavnagar',
    'Gandhinagar',
    'Jamnagar',
    'Junagadh',
    'Kutch',
    'Mehsana',
    'Rajkot',
    'Surat',
    'Vadodara',
    'Valsad',
  ],
  Haryana: [
    'Ambala',
    'Faridabad',
    'Gurugram',
    'Hisar',
    'Karnal',
    'Kurukshetra',
    'Panipat',
    'Rohtak',
    'Sonipat',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kullu',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],
  Jharkhand: [
    'Bokaro',
    'Dhanbad',
    'Dumka',
    'Hazaribagh',
    'Jamshedpur',
    'Ranchi',
    'Deoghar',
    'Giridih',
  ],
  Karnataka: [
    'Ballari',
    'Belagavi',
    'Bengaluru',
    'Bidar',
    'Chikkamagaluru',
    'Dakshina Kannada',
    'Dharwad',
    'Gulbarga',
    'Hassan',
    'Hubballi',
    'Mangaluru',
    'Mysuru',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
  ],
  Kerala: [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kannur',
    'Kasaragod',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Gwalior',
    'Indore',
    'Jabalpur',
    'Rewa',
    'Sagar',
    'Satna',
    'Ujjain',
  ],
  Maharashtra: [
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  Manipur: ['Bishnupur', 'Churachandpur', 'Imphal', 'Senapati', 'Thoubal', 'Ukhrul'],
  Meghalaya: ['East Garo Hills', 'East Khasi Hills', 'Jaintia Hills', 'Shillong', 'West Garo Hills', 'West Khasi Hills'],
  Mizoram: ['Aizawl', 'Champhai', 'Kolasib', 'Lunglei', 'Mamit', 'Serchhip'],
  Nagaland: ['Dimapur', 'Kohima', 'Mokokchung', 'Mon', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
  Odisha: [
    'Angul',
    'Balasore',
    'Bargarh',
    'Bhadrak',
    'Cuttack',
    'Ganjam',
    'Jharsuguda',
    'Kendrapara',
    'Khordha',
    'Puri',
    'Rourkela',
    'Sambalpur',
  ],
  Punjab: [
    'Amritsar',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Ferozepur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Ludhiana',
    'Mohali',
    'Patiala',
    'Rupnagar',
    'Sangrur',
  ],
  Rajasthan: [
    'Ajmer',
    'Alwar',
    'Bikaner',
    'Bhilwara',
    'Chittorgarh',
    'Jaipur',
    'Jaisalmer',
    'Jodhpur',
    'Kota',
    'Sikar',
    'Udaipur',
  ],
  Sikkim: ['East Sikkim', 'Gangtok', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dindigul',
    'Erode',
    'Kanchipuram',
    'Madurai',
    'Salem',
    'Thanjavur',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tiruppur',
    'Vellore',
  ],
  Telangana: [
    'Adilabad',
    'Hyderabad',
    'Karimnagar',
    'Khammam',
    'Mahbubnagar',
    'Medak',
    'Nalgonda',
    'Nizamabad',
    'Rangareddy',
    'Warangal',
  ],
  Tripura: ['Agartala', 'Dhalai', 'North Tripura', 'South Tripura', 'West Tripura'],
  'Uttar Pradesh': [
    'Agra',
    'Aligarh',
    'Allahabad',
    'Bareilly',
    'Ghaziabad',
    'Gorakhpur',
    'Jhansi',
    'Kanpur',
    'Lucknow',
    'Mathura',
    'Meerut',
    'Moradabad',
    'Noida',
    'Prayagraj',
    'Varanasi',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Rishikesh',
    'Roorkee',
    'Rudrapur',
    'Udham Singh Nagar',
  ],
  'West Bengal': [
    'Asansol',
    'Bardhaman',
    'Darjeeling',
    'Durgapur',
    'Howrah',
    'Kolkata',
    'Malda',
    'Murshidabad',
    'Nadia',
    'North 24 Parganas',
    'Siliguri',
    'South 24 Parganas',
  ],
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'Port Blair', 'South Andaman'],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  Delhi: [
    'Central Delhi',
    'East Delhi',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Shahdara',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
  ],
  'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Jammu', 'Kathua', 'Pulwama', 'Srinagar', 'Udhampur'],
  Ladakh: ['Kargil', 'Leh'],
  Lakshadweep: ['Kavaratti'],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
};

const STATE_ALIASES: Record<string, string> = {
  महाराष्ट्र: 'Maharashtra',
  मुंबई: 'Mumbai',
  दिल्ली: 'Delhi',
  गोवा: 'Goa',
  गुजरात: 'Gujarat',
  कर्नाटक: 'Karnataka',
  केरळ: 'Kerala',
  केरल: 'Kerala',
  राजस्थान: 'Rajasthan',
  पंजाब: 'Punjab',
  हरियाणा: 'Haryana',
  बिहार: 'Bihar',
  ओडिशा: 'Odisha',
  तेलंगणा: 'Telangana',
  तेलंगाना: 'Telangana',
  तमिलनाडु: 'Tamil Nadu',
  तामिळनाडू: 'Tamil Nadu',
  पश्चिमबंगाल: 'West Bengal',
  'पश्चिम बंगाल': 'West Bengal',
  उत्तराखंड: 'Uttarakhand',
  'उत्तर प्रदेश': 'Uttar Pradesh',
  मध्यप्रदेश: 'Madhya Pradesh',
  'मध्य प्रदेश': 'Madhya Pradesh',
  छत्तीसगढ़: 'Chhattisgarh',
  झारखंड: 'Jharkhand',
  असम: 'Assam',
  आंध्रप्रदेश: 'Andhra Pradesh',
  'आंध्र प्रदेश': 'Andhra Pradesh',
};

const CITY_ALIASES: Record<string, string> = {
  मुंबई: 'Mumbai',
  पुणे: 'Pune',
  नागपूर: 'Nagpur',
  नाशिक: 'Nashik',
  ठाणे: 'Thane',
  औरंगाबाद: 'Aurangabad',
  कोल्हापूर: 'Kolhapur',
  सोलापूर: 'Solapur',
  दिल्ली: 'Delhi',
  'नवी दिल्ली': 'New Delhi',
  बेंगलुरु: 'Bengaluru',
  चेन्नई: 'Chennai',
  कोलकाता: 'Kolkata',
  हैदराबाद: 'Hyderabad',
  अहमदाबाद: 'Ahmedabad',
  जयपुर: 'Jaipur',
  लखनऊ: 'Lucknow',
  कानपूर: 'Kanpur',
};

export function normalizeStateName(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return '';
  if (STATE_ALIASES[trimmed]) return STATE_ALIASES[trimmed];
  const match = INDIAN_STATES.find(
    (state) => state.toLowerCase() === trimmed.toLowerCase(),
  );
  return match ?? trimmed;
}

export function normalizeCityName(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return '';
  if (CITY_ALIASES[trimmed]) return CITY_ALIASES[trimmed];
  return trimmed;
}

export function getCitiesForState(state: string): string[] {
  const normalized = normalizeStateName(state);
  const cities = CITIES_BY_STATE[normalized];
  return cities ? [...cities] : [];
}

export function isCityInState(city: string, state: string): boolean {
  const normalizedCity = normalizeCityName(city);
  if (!normalizedCity) return false;
  return getCitiesForState(state).some(
    (item) => item.toLowerCase() === normalizedCity.toLowerCase(),
  );
}
