import type { LetterType } from '@/lib/letters/templates';

export const MR_TEMPLATE_HTML: Record<LetterType, string> = {
  'general': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">
  <style>
    .var { font-weight: bold; }
    .top-row { display: flex; justify-content: space-between; margin-bottom: 18px; }
    .recipient { margin-bottom: 14px; font-weight: normal; }
    .subject { font-weight: bold; margin-bottom: 14px; }
    .paragraph { text-align: justify; text-indent: 35px; margin: 0 0 8px 0; padding: 0; font-weight: normal; }
    .paragraph:last-of-type { margin-bottom: 0; }
  </style>
  <div class="top-row">
    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>
    <div>दि. <span class="var">{{date}}</span></div>
  </div>
  <div class="recipient">{{toBlock}}</div>
  <div class="subject"><span style="font-weight: normal;">विषय:</span> <span class="var">{{subject}}</span></div>
  {{paragraphsBlock}}
  <div class="letter-closing">{{signatureBlock}}</div>
</div>`,
  'fees': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 13px; line-height: 1.55; color: #000; margin: 0; font-weight: normal;">
  <style>
    .var { font-weight: bold; }
    .top-row { display: flex; justify-content: space-between; margin-bottom: 12px; }
    .address { margin-bottom: 12px; font-weight: normal; }
    .subject { font-weight: bold; margin-bottom: 12px; }
    .salutation { margin-bottom: 6px; font-weight: normal; }
    .paragraph { text-align: justify; text-indent: 28px; margin: 0 0 8px 0; padding: 0; font-weight: normal; }
    .paragraph:last-of-type { margin-bottom: 0; }
    .right-tab { text-align: right; padding-right: 36px; margin-top: 18px; font-weight: normal; }
    .right-tab-sign { text-align: right; padding-right: 28px; margin-top: 75px; font-weight: normal; }
  </style>
  <div class="top-row">
    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>
    <div>दि. <span class="var">{{date}}</span></div>
  </div>
  <div class="address">
    प्रति,<br>
    मुख्याध्यापक / प्राचार्य,<br>
    <span style="font-weight: normal;">{{schoolName}}</span><br>
    <span style="font-weight: normal;">{{schoolAddress}}</span>
  </div>
  <div class="subject">
    <span style="font-weight: normal;">विषय:</span> <span class="var">{{standard}}</span> मधील <span class="var">{{studentName}}</span> या विद्यार्थ्यास शुल्क सवलतीसाठी विनंती
  </div>
  <div class="salutation">
    महोदय/महोदया,
  </div>
  <p class="paragraph">
    सदर पत्राद्वारे आपणास विनंती करण्यात येत आहे की, आपल्या शाळेत <span class="var">{{standard}}</span> मध्ये शिकत असलेल्या <span class="var">{{studentName}}</span> या विद्यार्थ्यास शुल्क सवलत मंजूर करावी.
  </p>
  <p class="paragraph">
    सदर विद्यार्थ्याच्या पालकांची आर्थिक परिस्थिती अत्यंत हलाखीची असून, सध्या संपूर्ण शुल्क भरणे त्यांना शक्य नाही. म्हणून, आपण कृपया सहानुभूतीपूर्वक विचार करून संपूर्ण किंवा अंशतः शुल्क सवलत द्यावी, तसेच शुल्क भरण्यासाठी थोडा अधिक कालावधी आणि/किंवा हप्त्यांमध्ये भरण्याची सुविधा उपलब्ध करून द्यावी, ही नम्र विनंती आहे.
  </p>
  <p class="paragraph">
    तसेच, कृपया सदर विद्यार्थ्यास नियमित शाळेत/कॉलेजमध्ये हजर राहण्याची परवानगी द्यावी, जेणेकरून सदर विद्यार्थ्याच्या शिक्षणावर कोणताही परिणाम होणार नाही.
  </p>
  <p class="paragraph">
    आपण या प्रकरणाचा सहानुभूतीपूर्वक विचार करून सकारात्मक निर्णय घ्याल, अशी अपेक्षा आहे.
  </p>
  <div class="letter-closing">
  <div class="right-tab">
    आपली विश्वासू,
  </div>
  <div class="right-tab-sign">
    (<span class="var">{{signatory}}</span>)
  </div>
  </div>
</div>`,
  'school-admission': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    प्रति,<br>    मुख्याध्यापक / प्राचार्य,<br>    <span style="font-weight: normal;">{{schoolName}}</span><br>    <span style="font-weight: normal;">{{schoolAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> <span class="var">{{studentName}}</span> या विद्यार्थ्यास इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश मिळण्याबाबत शिफारस.  </div>  <div class="salutation">    महोदय/महोदया,  </div>  <p class="paragraph">    सदर पत्राद्वारे आपणास विनंती करण्यात येत आहे की, <span class="var">{{parentName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांचे पाल्य <span class="var">{{studentName}}</span> यास आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश मिळण्याकरिता आपणाकडे शिफारस करण्यात येत आहे.  </p>  <p class="paragraph">    सदर विद्यार्थ्यास शिक्षणाची आवड असून, पुढील शिक्षणासाठी योग्य शैक्षणिक वातावरण मिळणे आवश्यक आहे. आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश मिळाल्यास सदर विद्यार्थ्याच्या शिक्षणास निश्चितच मदत होईल.  </p>  <p class="paragraph">    <span class="var">{{reasonText}}</span>  </p>  <p class="paragraph">    तरी उपलब्ध जागा, प्रवेश नियम व आवश्यक कागदपत्रांची पडताळणी करून सदर विद्यार्थ्यास आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश देण्याबाबत सहानुभूतीपूर्वक व नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'school-transfer': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    प्रति,<br>    मुख्याध्यापक / प्राचार्य,<br>    <span style="font-weight: normal;">{{schoolName}}</span><br>    <span style="font-weight: normal;">{{schoolAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> <span class="var">{{studentName}}</span> या विद्यार्थ्यास इयत्ता <span class="var">{{standard}}</span> मध्ये स्थानांतरणाद्वारे प्रवेश मिळण्याबाबत शिफारस.  </div>  <div class="salutation">    महोदय/महोदया,  </div>  <p class="paragraph">    सदर पत्राद्वारे आपणास विनंती करण्यात येत आहे की, <span class="var">{{parentName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांचे पाल्य <span class="var">{{studentName}}</span> यास आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये स्थानांतरणाद्वारे प्रवेश मिळण्याकरिता आपणाकडे शिफारस करण्यात येत आहे.  </p>  <p class="paragraph">    सदर विद्यार्थी सध्या <span class="var">{{previousSchoolName}}</span> येथे इयत्ता <span class="var">{{currentStandard}}</span> मध्ये शिक्षण घेत असून, <span class="var">{{transferReason}}</span> या कारणास्तव आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश घेणे आवश्यक झाले आहे.  </p>  <p class="paragraph">    सदर विद्यार्थ्याच्या शिक्षणात खंड पडू नये व त्याचे पुढील शिक्षण सुरळीतपणे सुरू राहावे, याकरिता आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये प्रवेश मिळणे अत्यंत आवश्यक आहे.  </p>  <p class="paragraph">    तरी उपलब्ध जागा, प्रवेश नियम, शाळा सोडल्याचा दाखला / ट्रान्सफर सर्टिफिकेट आणि आवश्यक कागदपत्रांची पडताळणी करून सदर विद्यार्थ्यास आपल्या शाळेत इयत्ता <span class="var">{{standard}}</span> मध्ये स्थानांतरणाद्वारे प्रवेश देण्याबाबत सहानुभूतीपूर्वक व नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'ration-new': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> नवीन शिधापत्रिका मिळण्याबाबत.  </div>  <p class="paragraph">    सदर पत्रासोबत अर्जदार <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांना नवीन शिधापत्रिका मिळण्याकरिता आपणाकडे पाठवीत आहोत.  </p>  <p class="paragraph">    अर्जदाराने नवीन शिधापत्रिका मिळण्यासाठी आवश्यक कागदपत्रांसह अर्ज सादर केला असून, खालील कुटुंबीयांची नावे सदर नवीन शिधापत्रिकेत समाविष्ट करण्याबाबत विनंती करण्यात येत आहे:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    तरी अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून नवीन शिधापत्रिका मंजूर करण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    प्रति,<br>    शिधावाटप अधिकारी,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-add-members': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> शिधापत्रिकेत नाव समाविष्ट करण्याबाबत.  </div>  <p class="paragraph">    सदर पत्रासोबत अर्जदार <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांना त्यांच्या शिधापत्रिकेत कुटुंबातील सदस्यांची नावे समाविष्ट करण्याकरिता आपणाकडे पाठवीत आहोत.  </p>  <p class="paragraph">    अर्जदाराकडील शिधापत्रिका क्रमांक <span class="var">{{rationCardNo}}</span> असून, खालील सदस्यांची नावे सदर शिधापत्रिकेत समाविष्ट करण्याबाबत विनंती करण्यात येत आहे:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    तरी अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून सदर सदस्यांची नावे शिधापत्रिकेत समाविष्ट करण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    प्रति,<br>    शिधावाटप अधिकारी,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-delete-members': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> शिधापत्रिकेतून नाव वगळण्याबाबत.  </div>  <p class="paragraph">    सदर पत्रासोबत अर्जदार <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांना त्यांच्या शिधापत्रिकेतून कुटुंबातील सदस्यांची नावे वगळण्याकरिता आपणाकडे पाठवीत आहोत.  </p>  <p class="paragraph">    अर्जदाराकडील शिधापत्रिका क्रमांक <span class="var">{{rationCardNo}}</span> असून, खालील सदस्यांची नावे सदर शिधापत्रिकेतून वगळण्याबाबत विनंती करण्यात येत आहे:  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    तरी अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून सदर सदस्यांची नावे शिधापत्रिकेतून वगळण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    प्रति,<br>    शिधावाटप अधिकारी,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'ration-transfer': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }    .recipient {      margin-top: 25px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> शिधापत्रिका एका शिधावाटप कार्यालयातून दुसऱ्या शिधावाटप कार्यालयात हस्तांतरित करण्याबाबत.  </div>  <p class="paragraph">    सदर पत्रासोबत अर्जदार <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> यांना त्यांच्या शिधापत्रिकेचे हस्तांतरण करण्याकरिता आपणाकडे पाठवीत आहोत.  </p>  <p class="paragraph">    अर्जदाराकडील शिधापत्रिका क्रमांक <span class="var">{{rationCardNo}}</span> असून, सदर शिधापत्रिका <span class="var">{{fromRationOffice}}</span> येथून <span class="var">{{toRationOffice}}</span> येथे हस्तांतरित करण्याबाबत विनंती करण्यात येत आहे.  </p>  <p class="paragraph">    अर्जदाराच्या निवासस्थानात बदल झाल्यामुळे / क्षेत्र बदल झाल्यामुळे सदर शिधापत्रिका संबंधित नवीन शिधावाटप कार्यालयाच्या कार्यक्षेत्रात वर्ग करणे आवश्यक आहे.  </p>  <p class="paragraph">    <span class="var">{{familyMembersBlock}}</span>  </p>  <p class="paragraph">    तरी अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून सदर शिधापत्रिका <span class="var">{{toRationOffice}}</span> येथे हस्तांतरित करण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div>  <div class="recipient">    प्रति,<br>    शिधावाटप अधिकारी,<br>    <span style="font-weight: normal;">{{rationOfficeAddress}}</span>  </div></div>`,
  'income': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    प्रति,<br>    संबंधित अधिकारी,<br>    <span style="font-weight: normal;">{{officeName}}</span><br>    <span style="font-weight: normal;">{{officeAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> <span class="var">{{fullName}}</span> यांना उत्पन्न प्रमाणपत्र मिळण्याबाबत.  </div>  <div class="salutation">    महोदय/महोदया,  </div>  <p class="paragraph">    सदर पत्राद्वारे आपणास कळविण्यात येते की, <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> <span class="var">{{genderPronounSubject}}</span> वरील पत्त्यावर वास्तव्यास आहेत.  </p>  <p class="paragraph">    सदर अर्जदारांचा आधार क्रमांक <span class="var">{{aadhaarNo}}</span> असा असून, त्यांनी दिलेल्या माहितीनुसार त्यांचे वार्षिक उत्पन्न रु. <span class="var">{{annualIncome}}</span>/- इतके आहे.  </p>  <p class="paragraph">    सदर प्रमाणपत्र / शिफारसपत्र अर्जदाराच्या विनंतीनुसार देण्यात येत आहे.  </p>  <p class="paragraph">    तरी सदर अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून उत्पन्न प्रमाणपत्र देण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
  'domicile': `<div class="letter-content" style="white-space: normal; font-family: inherit; font-size: 15px; line-height: 1.75; color: #000; margin: 0;">  <style>    .var {      font-weight: bold;    }    .top-row {      display: flex;      justify-content: space-between;      margin-bottom: 18px;    }    .recipient {      margin-bottom: 14px;    }    .subject {      font-weight: bold;      margin-bottom: 14px;    }    .salutation {      margin-bottom: 6px;    }    .paragraph {      text-align: justify;      text-indent: 35px;      margin: 0;      padding: 0;    }    .signature {      text-align: right;      padding-right: 35px;      margin-top: 95px;    }  </style>  <div class="top-row">    <div>संदर्भ क्र. <span class="var">{{referencePrefix}}</span>/<span class="var">{{referenceNo}}</span></div>    <div>दि. <span class="var">{{date}}</span></div>  </div>  <div class="recipient">    प्रति,<br>    संबंधित अधिकारी,<br>    <span style="font-weight: normal;">{{officeName}}</span><br>    <span style="font-weight: normal;">{{officeAddress}}</span>  </div>  <div class="subject">    <span style="font-weight: normal;">विषय:</span> <span class="var">{{fullName}}</span> यांना अधिवास / रहिवासी प्रमाणपत्र मिळण्याबाबत.  </div>  <div class="salutation">    महोदय/महोदया,  </div>  <p class="paragraph">    सदर पत्राद्वारे आपणास कळविण्यात येते की, <span class="var">{{salutation}}</span> <span class="var">{{fullName}}</span>, रा. <span style="font-weight: normal;">{{address}}</span> <span class="var">{{genderPronounSubject}}</span> वरील पत्त्यावर दीर्घ काळापासून वास्तव्यास आहेत.  </p>  <p class="paragraph">    सदर अर्जदारांचा आधार क्रमांक <span class="var">{{aadhaarNo}}</span> असा असून, त्यांनी अधिवास / रहिवासी प्रमाणपत्र मिळण्याकरिता विनंती केली आहे.  </p>  <p class="paragraph">    तरी सदर अर्जदाराकडे असलेल्या पुरावादर्शक कागदपत्रांची पडताळणी करून अधिवास / रहिवासी प्रमाणपत्र देण्याबाबत नियमानुसार आवश्यक ती कार्यवाही करण्यात यावी, ही विनंती.  </p>  <div class="signature">    (<span class="var">{{signatory}}</span>)  </div></div>`,
};
